### ISSUE TITLE
Logiclevel shifter for LED Dataline?

### ISSUE THREAD

**Issue by philippk80** [FabianRig/ArduinoMoonBoardLED#10]
Hello,
great work!
I have a question... dont you need a Logiclevel shifter for the data line because operating voltage of the arduino is 3.3v and LED are 5V?

**Comment by jordigrau83** [comment]
No, you can simply power the Arduino and the LEDS with 5V 1A USB

**Comment by marcosncosta1** [comment]
Has anyone tried with the official led lights + Arduino combo?

**Comment by FabianRig** [comment]
As @jordigrau83 has written: no need for a logic level shifter! 

@marcosncosta1: I'll close this issue and create a new one for your question.
