### ISSUE TITLE
How to download the ArduinoMoonBoardLED project

### ISSUE THREAD

**Issue by lucadona98** [FabianRig/ArduinoMoonBoardLED#13]
please can you explain to me how to download the ArduinoMonnboardLED project on platformio.
and from that passage onwards

please, I'm going crazy

**Comment by marcosncosta1** [comment]
The steps are described in the ReadMe file in detail. I can take some photos of the specific steps on the Visual Studio Code for you.

**Comment by FabianRig** [comment]
Hi @lucadona98!

As @marcosncosta1 wrote: you can find all details for both Windows and Linux in the README. For downloading, you can use git (clone the repository) or simply download the repository as a zip file!

Please let us know if that worked for you.

**Comment by lucadona98** [comment]
then I put the program on platformio. I start a run and it tells me that there are some packages missing to install, I install the missing packages, but it always tells me the same thing that the packages are missing.

**Comment by lucadona98** [comment]
then I put the program on platformio. I start a run and it tells me that there are some packages missing to install, I install the missing packages, but it always tells me the same thing that the packages are missing.

**Comment by FabianRig** [comment]
Please follow the instructions in the README. 

If there are any errors along the way, copy/paste them here (and format them as code). Explain in detail what you did (what buttons/menus you clicked, what happened etc.). We need to know the details in order to help you. "some packages mssing" is not specific enough.

**Comment by FabianRig** [comment]
It seems that I can close this issue. Feel free to re-open it.
