### ISSUE TITLE
Compiling issue

### ISSUE THREAD

**Issue by DashCodingSecondAcc** [FabianRig/ArduinoMoonBoardLED#23]
Hi. 
i am following the Linux install ReadMe and everything works fine, except for the compile step, which gives me this error:
sh: 1: arm-none-eabi-g++: not found

![image](https://github.com/FabianRig/ArduinoMoonBoardLED/assets/110558233/fb03dd7c-e3f7-44c0-a4b1-dbd97f3a5a70)

please help. Great project, would love to get itworking!

**Comment by DenkBrettl** [comment]
At a first glance I suspect it has to do with you using a RaspberryPi. Any chance to try on an x86 machine? If not, could you search the internet for the error and try to follow the advice you can find for it?

**Comment by DashCodingSecondAcc** [comment]
Fixed it :) it was my bad - I just used VS code instead.
